### ISSUE TITLE
Trying to setup with nginx

### ISSUE THREAD

**Issue by bad-mdgk** [AuspeXeu/openvpn-status#14]
Hello. I am install this app on Ubuntu 16.04 LTS on a VPS server.
And I can't connect to web-page, even considering successful installation process.
Also Have VESTA installed on this server, and added exceptions for 3013 port on firewall.

nodejs v6.14.2
_cfg.json_
```
{
  "port": 3013,
  "bind": 127.0.0.1,
  "servers": [{"name": "VPN Server"}],
  "ipFile": "./GeoLite2-City.mmdb"
}

```
_status.sh_
```
#!/bin/bash
HOST="127.0.0.1"
PORT="3013"
SERVER="0"

JSON="{\"script\":\"$script_type\",\"pub\":\"$trusted_ip\",\"cn\":\"$common_name\",\"user\":\"$username\",\"vpn\":\"$ifconfig_pool_remote_ip\"}"
curl -H "Content-Type: application/json" -X POST -d "$JSON" "http://$HOST:$PORT/server/$SERVER/script" --connect-timeout 2 -m 3
exit 0

```

and added this code to _nginx.conf_
```
server {
  listen 80;
  server_name mydomain.space;

  location / {
    proxy_pass http://127.0.0.1:3013
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_read_timeout 86400;
  }
}
```

Also tried to change HOST to my VPS real IP-address, but nothing changes.

**Comment by AuspeXeu** [comment]
The HOST should not be changed. Did you make sure the node application is running?

**Comment by bad-mdgk** [comment]
`
chmod: cannot access 'status.sh': No such file or directory
`
How can I fix it? I've done all the instructions from README.md

Here is my server.conf
```
port 1194
proto udp
dev tun
sndbuf 0
rcvbuf 0
ca ca.crt
cert server.crt
key server.key
dh dh.pem
auth SHA512
tls-auth ta.key 0
topology subnet
server 10.8.0.0 255.255.255.0
ifconfig-pool-persist ipp.txt
push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS 1.1.1.1"
push "dhcp-option DNS 1.0.0.1"
keepalive 10 120
cipher AES-256-CBC
comp-lzo
user nobody
group nogroup
persist-key
persist-tun
status openvpn-status.log
verb 3
crl-verify crl.pem
script-security 2
client-connect ./status.sh
client-disconnect ./status.sh

```

**Comment by AuspeXeu** [comment]
Try `sudo chmod +x status.sh`

**Comment by bad-mdgk** [comment]
Same  :weary:

**Comment by AuspeXeu** [comment]
Oh, didn't read your error fully ... you need to move the `status.sh` into the same folder like your `server.conf`

**Comment by bad-mdgk** [comment]
Thats the problem, I already have `status.sh` on `server.conf` directory. But openvpn daemon still can't execute it....

**Comment by AuspeXeu** [comment]
Well, it needs to be executable by the same user like your openvpn daemon. But your chmod error says the file does not exist?

**Comment by bad-mdgk** [comment]
Yes it is.

**Comment by AuspeXeu** [comment]
Well, I don't know what to tell you then. Restart the daemon

**Comment by bad-mdgk** [comment]
Restarted openvpn daemon but nothing changes.

I must execute `chmod +x status.sh` command from /root/ ?
Like `root@server:~#` How it tells readme.md, right?

Just execute this command from /openvpn/ directory and no errors and any answers.

**Comment by AuspeXeu** [comment]
All you have to do is put the `status.sh` into the folder of the `server.conf` and then `chmod +x status.sh` that's it.

**Comment by bad-mdgk** [comment]
```
App name       │ id │ mode │ pid   │ status │ restart │ uptime │ cpu │ mem       │ user │ watching │
├────────────────┼────┼──────┼───────┼────────┼─────────┼────────┼─────┼───────────┼──────┼──────────┤
│ openvpn-status │ 0  │ fork │ 11472 │ online │ 0       │ 0s     │ 28% │ 18.9 MB   │ root │ disabled 
```
So I resume installation process and get the app online. 
And add this config to nginx:
```
server {
  listen 80;
  server_name mvpn.space;

  location / {
    proxy_pass http://127.0.0.1:3013;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_read_timeout 86400;
  }
}

```

How do i get to the web-page?

**Comment by AuspeXeu** [comment]
visit `mydomain.space` ?

**Comment by bad-mdgk** [comment]
I am change `location` to `/openvpn-status` and it works. Perhaps VESTA blocked `/` .
But now page is empty:

```
<div id="app">
<!-- built files will be auto injected -->
</div>
```

=(

**Comment by AuspeXeu** [comment]
Did you run `npm run build`?

**Comment by AuspeXeu** [comment]
I don't understand how you can get an empty page in that case. Can you check the log for errors?

**Comment by bad-mdgk** [comment]
`pm2 logs openvpn-status --lines 1000` 
says
```
0|openvpn- | Error: Error parsing your configuration file: [cfg.json]: Unexpected token . in JSON at position 31
0|openvpn- |     at File.loadSync (/root/openvpn-status/node_modules/nconf/lib/nconf/stores/file.js:170:11)
0|openvpn- |     at Provider.add (/root/openvpn-status/node_modules/nconf/lib/nconf/provider.js:136:23)
0|openvpn- |     at Provider.file (/root/openvpn-status/node_modules/nconf/lib/nconf/provider.js:63:15)
0|openvpn- |     at Object.<anonymous> (/root/openvpn-status/server.js:17:6)
0|openvpn- |     at Module._compile (module.js:577:32)
0|openvpn- |     at Object.Module._extensions..js (module.js:586:10)
0|openvpn- |     at Module.load (module.js:494:32)
0|openvpn- |     at tryModuleLoad (module.js:453:12)
0|openvpn- |     at Function.Module._load (module.js:445:3)
0|openvpn- |     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:83:21)
0|openvpn- |     at Module._compile (module.js:577:32)
0|openvpn- |     at Object.Module._extensions..js (module.js:586:10)
0|openvpn- |     at Module.load (module.js:494:32)
0|openvpn- |     at tryModuleLoad (module.js:453:12)
0|openvpn- |     at Function.Module._load (module.js:445:3)
0|openvpn- |     at Module.runMain (module.js:611:10)
0|openvpn- |     at run (bootstrap_node.js:394:7)
0|openvpn- |     at startup (bootstrap_node.js:160:9)
0|openvpn- |     at bootstrap_node.js:507:3

``` 
many times

**Comment by bad-mdgk** [comment]
Well, now I have this on webpage
``` 
<body><div id="app"></div>
<script type="text/javascript"src="./static/js/manifest.3ad1d5771e9b13dbdad2.js"></script>
<script type="text/javascript" src="./static/js/vendor.802828d6c658a7554a2a.js"></script>
<script type="text/javascript" src="./static/js/app.c18d1d3d526a4b8b2468.js"></script>
</body>
```
but page is blank and I dont have `./static/js/` folder at all.
Any Ideas.. please?? :(

**Comment by AuspeXeu** [comment]
These folders are supposed to be in the `dist` folder. Are there any errors in your browser console?

**Comment by bad-mdgk** [comment]
Perhaps I did not configure the nginx properly...

Failed to load these resources: the server responded with a status of 403 
```
vendor.802828d6c658a7554a2a.js:1
manifest.3ad1d5771e9b13dbdad2.js:1
app.c18d1d3d526a4b8b2468.js:1 
manifest.3ad1d5771e9b13dbdad2.js:1  
app.b6a373e885004e7aa0795092dd09d73e.css:1
vendor.802828d6c658a7554a2a.js:1  
app.c18d1d3d526a4b8b2468.js:1
static/images/32x32.png:1 
static/images/16x16.png:1 
app.b6a373e885004e7aa0795092dd09d73e.css:1 
```

**Comment by bad-mdgk** [comment]
YAS, It worked. This was an issue

> I am change location to /openvpn-status and it works. Perhaps VESTA blocked / .

Changed servername to another domain and it works!
