### ISSUE TITLE
Docker run fails

### ISSUE THREAD

**Issue by 13bscsaamjad** [AuspeXeu/openvpn-status#202]
```
Error: Invalid Extended Type at offset 0 val 7
at Decoder.decode (/usr/src/app/node_modules/maxmind/lib/decoder.js:61:13)
at new Metadata (/usr/src/app/node_modules/maxmind/lib/metadata.js:15:26)at Reader.load (/usr/src/app/node_modules/maxmind/lib/reader.js:21:19)
at new Reader (/usr/src/app/node_modules/maxmind/lib/reader.js:15:8)
at /usr/src/app/node_modules/maxmind/index.js:24:20
at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
```

**Comment by AuspeXeu** [comment]
What command did you execute?

**Comment by 13bscsaamjad** [comment]
i ran the docker-compose.sample.yml file through docker-compose!
