### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Edll** [AuspeXeu/openvpn-status#257]
Hello,
thanks for your great tool. Sometimes the Server crash with the following error:

`(node:26909) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'Client ID' of undefined
    at mkClient (/opt/openvpn-status/openvpn.js:5:14)
    at getClients.then (/opt/openvpn-status/openvpn.js:97:39)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:26909) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:26909) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
/opt/openvpn-status/openvpn.js:86
      const [_, clientId, received, sent] = data.match(/>BYTECOUNT_CLI:([0-9]+),([0-9]+),([0-9]+)/).map(itm => parseInt(itm, 10))
                                                                                                   ^

TypeError: Cannot read property 'map' of null
    at client.procData (/opt/openvpn-status/openvpn.js:86:100)
    at items.forEach.itm (/opt/openvpn-status/openvpn.js:31:33)
    at Array.forEach (<anonymous>)
    at Socket.socket.on.data (/opt/openvpn-status/openvpn.js:31:13)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
`

**Comment by Edll** [comment]
there is a similar problem in openvpn.js i fixed it with the following line 9:

`pub: client['Real Address'] == undefined ? 'n/a' : client['Real Address'].split(':')[0],`

**Comment by AuspeXeu** [comment]
Can you try replacing line 66 with
```
if (((vpnClient['Common Name'] && vpnClient['Common Name'].toString().length) || (vpnClient.Username && vpnClient.Username.toString().length)) && vpnClient['Client ID'])
```
And report back if this fixes your issue? :)

**Comment by Edll** [comment]
I'll try and give you feedback.

**Comment by AuspeXeu** [comment]
@Edll any update on this?

**Comment by Edll** [comment]
It seems like the problem was solved so we didn't have a crash anymore. Thanks for help.

**Comment by AuspeXeu** [comment]
You tried it with my suggestion or yours?

**Comment by Edll** [comment]
with yours.
