### ISSUE TITLE
Docker & NPM install problem

### ISSUE THREAD

**Issue by tientmse62290** [AuspeXeu/openvpn-status#427]
I tried to install with npm but have problems:

```
npm install

> sqlite3@4.1.1 install /home/tientm/openvpnstatus/openvpn-status/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

sh: node-pre-gyp: command not found
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: abbrev@1.1.1 (node_modules/fsevents/node_modules/abbrev):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/abbrev' -> '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/.abbrev.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ansi-regex@2.1.1 (node_modules/fsevents/node_modules/ansi-regex):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/ansi-regex' -> '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/.ansi-regex.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: aproba@1.2.0 (node_modules/fsevents/node_modules/aproba):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/aproba' -> '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/.aproba.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: balanced-match@1.0.0 (node_modules/fsevents/node_modules/balanced-match):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/balanced-match' -> '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/.balanced-match.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: chownr@1.1.3 (node_modules/fsevents/node_modules/chownr):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/chownr' -> '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/.chownr.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: code-point-at@1.1.0 (node_modules/fsevents/node_modules/code-point-at):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/code-point-at' -> '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/.code-point-at.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: concat-map@0.0.1 (node_modules/fsevents/node_modules/concat-map):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/concat-map' -> '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/.concat-map.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: console-control-strings@1.1.0 (node_modules/fsevents/node_modules/console-control-strings):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/console-control-strings' -> '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/.console-control-strings.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: core-util-is@1.0.2 (node_modules/fsevents/node_modules/core-util-is):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/core-util-is' -> '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/.core-util-is.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: deep-extend@0.6.0 (node_modules/fsevents/node_modules/deep-extend):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/deep-extend' -> '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/.deep-extend.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: delegates@1.0.0 (node_modules/fsevents/node_modules/delegates):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/delegates' -> '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/.delegates.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: detect-libc@1.0.3 (node_modules/fsevents/node_modules/detect-libc):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/detect-libc' -> '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/.detect-libc.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fs.realpath@1.0.0 (node_modules/fsevents/node_modules/fs.realpath):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/fs.realpath' -> '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/.fs.realpath.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: has-unicode@2.0.1 (node_modules/fsevents/node_modules/has-unicode):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/has-unicode' -> '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/.has-unicode.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: inherits@2.0.4 (node_modules/fsevents/node_modules/inherits):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/inherits' -> '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/.inherits.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ini@1.3.5 (node_modules/fsevents/node_modules/ini):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/ini' -> '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/.ini.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: isarray@1.0.0 (node_modules/fsevents/node_modules/isarray):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/isarray' -> '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/.isarray.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: minimist@0.0.8 (node_modules/fsevents/node_modules/minimist):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/minimist' -> '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/.minimist.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ms@2.1.2 (node_modules/fsevents/node_modules/ms):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/ms' -> '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/.ms.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: npm-normalize-package-bin@1.0.1 (node_modules/fsevents/node_modules/npm-normalize-package-bin):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/npm-normalize-package-bin' -> '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/.npm-normalize-package-bin.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: number-is-nan@1.0.1 (node_modules/fsevents/node_modules/number-is-nan):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/number-is-nan' -> '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/.number-is-nan.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: object-assign@4.1.1 (node_modules/fsevents/node_modules/object-assign):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/object-assign' -> '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/.object-assign.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: os-homedir@1.0.2 (node_modules/fsevents/node_modules/os-homedir):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/os-homedir' -> '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/.os-homedir.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: os-tmpdir@1.0.2 (node_modules/fsevents/node_modules/os-tmpdir):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/os-tmpdir' -> '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/.os-tmpdir.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: path-is-absolute@1.0.1 (node_modules/fsevents/node_modules/path-is-absolute):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/path-is-absolute' -> '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/.path-is-absolute.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: process-nextick-args@2.0.1 (node_modules/fsevents/node_modules/process-nextick-args):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/process-nextick-args' -> '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/.process-nextick-args.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: minimist@1.2.0 (node_modules/fsevents/node_modules/rc/node_modules/minimist):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/rc/node_modules/minimist' -> '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/rc/node_modules/.minimist.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: safe-buffer@5.1.2 (node_modules/fsevents/node_modules/safe-buffer):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/safe-buffer' -> '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/.safe-buffer.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: safer-buffer@2.1.2 (node_modules/fsevents/node_modules/safer-buffer):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/safer-buffer' -> '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/.safer-buffer.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sax@1.2.4 (node_modules/fsevents/node_modules/sax):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/sax' -> '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/.sax.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: semver@5.7.1 (node_modules/fsevents/node_modules/semver):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/semver' -> '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/.semver.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: set-blocking@2.0.0 (node_modules/fsevents/node_modules/set-blocking):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/set-blocking' -> '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/.set-blocking.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: signal-exit@3.0.2 (node_modules/fsevents/node_modules/signal-exit):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/signal-exit' -> '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/.signal-exit.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: strip-json-comments@2.0.1 (node_modules/fsevents/node_modules/strip-json-comments):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/strip-json-comments' -> '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/.strip-json-comments.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: util-deprecate@1.0.2 (node_modules/fsevents/node_modules/util-deprecate):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/util-deprecate' -> '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/.util-deprecate.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: wrappy@1.0.2 (node_modules/fsevents/node_modules/wrappy):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/wrappy' -> '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/.wrappy.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: yallist@3.1.1 (node_modules/fsevents/node_modules/yallist):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/yallist' -> '/home/tientm/openvpnstatus/openvpn-status/node_modules/fsevents/node_modules/.yallist.DELETE'

npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! sqlite3@4.1.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the sqlite3@4.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-13T03_50_57_742Z-debug.log
```

Then I try with docker:
after change file docker-compose.sample.yml => docker-compose.yml and run
`docker-compose up docker-compose.yml`
I got error:
`ERROR: In file './docker-compose.yml', service 'image' must be a mapping not a string.`

Any solutions?
Thanks

**Comment by tientmse62290** [comment]
Then I update node to version 12, run "node server.js" and got:
```
assert.js:43
  throw new errors.AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: Apparently you are using old version of node. Please upgrade to node 10.4.x or above.
    at Object.<anonymous> (/home/tientm/openvpnstatus/openvpn-status/node_modules/maxmind/lib/decoder.js:9:17)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/tientm/openvpnstatus/openvpn-status/node_modules/maxmind/lib/reader.js:6:35)
    at Module._compile (module.js:653:30)
```

**Comment by tientmse62290** [comment]
updated node:
```
node server.js
/home/tientm/openvpnstatus/openvpn-status/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:81
        throw new Error(`Please install ${moduleName} package manually`);
        ^

Error: Please install sqlite3 package manually
    at ConnectionManager._loadDialectModule (/home/tientm/openvpnstatus/openvpn-status/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:81:15)
    at new ConnectionManager (/home/tientm/openvpnstatus/openvpn-status/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:22:21)
    at new SqliteDialect (/home/tientm/openvpnstatus/openvpn-status/node_modules/sequelize/lib/dialects/sqlite/index.js:14:30)
    at new Sequelize (/home/tientm/openvpnstatus/openvpn-status/node_modules/sequelize/lib/sequelize.js:324:20)
    at Object.<anonymous> (/home/tientm/openvpnstatus/openvpn-status/database.js:3:19)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/tientm/openvpnstatus/openvpn-status/server.js:11:12)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

```

**Comment by AuspeXeu** [comment]
Try the latest version of the yml file https://github.com/AuspeXeu/openvpn-status/blob/master/docker-compose.sample.yml

**Comment by tientmse62290** [comment]
Tried and got error:
```
docker-compose up docker-compose.yml
ERROR: No such service: docker-compose.yml
```

**Comment by tientmse62290** [comment]
```
docker-compose up
Creating openvpn-status ... error

ERROR: for openvpn-status  Cannot start service openvpn-status: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/home/tientm/openvpnstatus/openvpn-status/status-cfg/cfg.json\\\" to rootfs \\\"/var/lib/docker/overlay2/406fa5adfda5fc318686fbe20afcbf25bb4c7434b264b71d33ac0ea203f8fd7a/merged\\\" at \\\"/var/lib/docker/overlay2/406fa5adfda5fc318686fbe20afcbf25bb4c7434b264b71d33ac0ea203f8fd7a/merged/usr/src/app/cfg.json\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for openvpn-status  Cannot start service openvpn-status: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/home/tientm/openvpnstatus/openvpn-status/status-cfg/cfg.json\\\" to rootfs \\\"/var/lib/docker/overlay2/406fa5adfda5fc318686fbe20afcbf25bb4c7434b264b71d33ac0ea203f8fd7a/merged\\\" at \\\"/var/lib/docker/overlay2/406fa5adfda5fc318686fbe20afcbf25bb4c7434b264b71d33ac0ea203f8fd7a/merged/usr/src/app/cfg.json\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.

```

**Comment by AuspeXeu** [comment]
Are you on a windows machine?

**Comment by tientmse62290** [comment]
I'm very new to docker so I will describe steps I use:
1. download the docker-compose.yml and edit evironment variables
2. pull image from docker
3. run: docker-compose up docker-compose.yml
Is it true?

**Comment by AuspeXeu** [comment]
1. correct
2. not needed
3. `docker-compose up -d`
4. `docker ps` to check it's running
5. `docker logs openvpn-status` to see the log

**Comment by tientmse62290** [comment]
Thank you very much. It works.
But I dont see any thing on it.
I'm using OpenVPN on PFSense 192.168.1.23
I config on server.conf with:
`management 0.0.0.0 5555`
In cfg.json:
`{"name": "PFSense2","host": "192.168.1.23","man_port": 5555}`
I run docker on server 192.168.1.17

**Comment by AuspeXeu** [comment]
Try to ping `192.168.1.23` from you docker image using `docker exec -it openvpn-status ping 192.168.1.23`

**Comment by tientmse62290** [comment]
It shows that docker can ping pfsense normally.
But I got some problem with OpenVPN on PFsense maybe
https://forum.netgate.com/topic/151355/config-management-interface-make-unable-to-contact-daemon
After I config management on pfsense, the openvpn got service error

**Comment by AuspeXeu** [comment]
I cannot help you with that ... not an expert with openvpn

**Comment by tientmse62290** [comment]
Thank you very much :D
