### ISSUE TITLE
"Disconnect client" does not work

### ISSUE THREAD

**Issue by sebelk** [AuspeXeu/openvpn-status#429]
If I click on skull icon, it does nothing, I've tested on Firefox and on Chromium.

On the shell it outputs the following error:

```
ReferenceError: clientId is not defined
    at /home/sergio/Descargas/openvpn-status/openvpn.js:144:91
    at Array.find (<anonymous>)
    at client.disconnect (/home/sergio/Descargas/openvpn-status/openvpn.js:144:54)
    at /home/sergio/Descargas/openvpn-status/server.js:96:36
    at Layer.handle [as handle_request] (/home/sergio/Descargas/openvpn-status/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/sergio/Descargas/openvpn-status/node_modules/express/lib/router/route.js:137:13)
    at validateServer (/home/sergio/Descargas/openvpn-status/server.js:90:3)
    at Layer.handle [as handle_request] (/home/sergio/Descargas/openvpn-status/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/sergio/Descargas/openvpn-status/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/sergio/Descargas/openvpn-status/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/sergio/Descargas/openvpn-status/node_modules/express/lib/router/layer.js:95:5)
    at /home/sergio/Descargas/openvpn-status/node_modules/express/lib/router/index.js:281:22
    at param (/home/sergio/Descargas/openvpn-status/node_modules/express/lib/router/index.js:354:14)
    at param (/home/sergio/Descargas/openvpn-status/node_modules/express/lib/router/index.js:365:14)
    at param (/home/sergio/Descargas/openvpn-status/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/home/sergio/Descargas/openvpn-status/node_modules/express/lib/router/index.js:410:3)
    at next (/home/sergio/Descargas/openvpn-status/node_modules/express/lib/router/index.js:275:10)
    at jsonParser (/home/sergio/Descargas/openvpn-status/node_modules/body-parser/lib/types/json.js:119:7)
    at Layer.handle [as handle_request] (/home/sergio/Descargas/openvpn-status/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/sergio/Descargas/openvpn-status/node_modules/express/lib/router/index.js:317:13)
    at /home/sergio/Descargas/openvpn-status/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/sergio/Descargas/openvpn-status/node_modules/express/lib/router/index.js:335:12)
```

Any ideas?

Thanks in advance!

**Comment by shenglong209** [comment]
in openvpn.js
change "client.clientId === clientId" to "client.clientId === cid"
`disconnect(cid) {
  const client = Array.from(this.clients.values()).find((client) => client.clientId === cid)
  if (!client)
    return
  this.socket.write(`client-kill ${cid}`)
  this.emit('client-disconnect', client)
}`

**Comment by AuspeXeu** [comment]
Fixed in the latest version, thanks!

**Comment by wgalafassijr** [comment]
On my setup the disconnection doesn't work, but i have not error.

**Comment by wgalafassijr** [comment]
with chrome 81.0.4044.129 works fine
but with firefox 75 don't

**Comment by fuzsh** [comment]
Hi, 
I get Error: Request failed with status code 400,
how can i know what's up with that ? ( it happens when i want to kill user)
@AuspeXeu

**Comment by AuspeXeu** [comment]
You have any server side log that shows an error?
