### ISSUE TITLE
Server crashing 

### ISSUE THREAD

**Issue by rajesh8614** [AuspeXeu/openvpn-status#432]
Thank you for this great tool

`/usr/src/app/openvpn.js:88
      const [pub, port] = props[this.clientProps.indexOf('Real Address')].split(':')
                                                                          ^

TypeError: Cannot read property 'split' of undefined
    at client.procData (/usr/src/app/openvpn.js:88:75)
    at /usr/src/app/openvpn.js:47:33
    at Array.forEach (<anonymous>)
    at Socket.<anonymous> (/usr/src/app/openvpn.js:47:13)
    at Socket.emit (events.js:311:20)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! openvpn-status@4.2.30 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the openvpn-status@4.2.30 start script.
`

**Comment by KarlStraussberger** [comment]
#444 fixes this issue for me, post your openvpn.log if not.

**Comment by KarlStraussberger** [comment]
May also be caused by a runtime issue where the socket only returns incomplete data. Im my case it contained only "192.168." instead of the full client line `"192.168.10.65,client,91.1.1.1:40160,Wed Apr  8 09:53:11 2020"`

**Comment by rajesh8614** [comment]
Hi 
Thank you!  @KarlStraussberger @AuspeXeu 
I have pulled new code from repository by command `git pull` under repo changes done
But I am seeing this error and server crashing
I am using Docker and 2 openvpn servers
entry of servers/server1.json
```{"name": "server1","host": "10.x.x.x","man_port": 7505}```
Kindly help me to find cause of this issue


```Unhandled rejection Error: WHERE parameter "node" has invalid "undefined" value
    at SQLiteQueryGenerator.whereItemQuery (/usr/src/app/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2184:13)
    at /usr/src/app/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2173:25
    at Array.forEach (<anonymous>)
    at SQLiteQueryGenerator.whereItemsQuery (/usr/src/app/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2171:35)
    at SQLiteQueryGenerator.getWhereConditions (/usr/src/app/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2583:19)
    at SQLiteQueryGenerator.selectQuery (/usr/src/app/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1315:28)
    at QueryInterface.select (/usr/src/app/node_modules/sequelize/lib/query-interface.js:1122:27)
    at /usr/src/app/node_modules/sequelize/lib/model.js:1757:34
    at tryCatcher (/usr/src/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/src/app/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/src/app/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/src/app/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/src/app/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/usr/src/app/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/usr/src/app/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/src/app/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/src/app/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
/usr/src/app/openvpn.js:88
      const [pub, port] = props[this.clientProps.indexOf('Real Address')].split(':')
                                                                          ^

TypeError: Cannot read property 'split' of undefined
    at client.procData (/usr/src/app/openvpn.js:88:75)
    at /usr/src/app/openvpn.js:47:33
    at Array.forEach (<anonymous>)
    at Socket.<anonymous> (/usr/src/app/openvpn.js:47:13)
    at Socket.emit (events.js:311:20)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! openvpn-status@4.2.30 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the openvpn-status@4.2.30 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-08T15_29_11_163Z-debug.log
```

**Comment by KarlStraussberger** [comment]
First of all you are still running the wrong version `openvpn-status@4.2.30`. It should be 4.2.32. (The correct line is 108 and looks different now!)

Additionally you have to add `"netmask": "<???>"` to your server config file.

**Comment by rajesh8614** [comment]
Its fine now.... I added netmask in `servers/server1.json` file and updated docker image with latest tag
```> openvpn-status@4.2.32 start /usr/src/app
> node server.js
```
Thanks! a lot

**Comment by rajesh8614** [comment]
Hi 
I am having this error again .
`Could not process data item ROUTING_TABLE       192.168.x.x    username 122.x.x.x:53989       Tue Apr 28 09:05:29 2020        1588044929`
 `` TypeError: Cannot read property 'split' of undefined
    at client.procData (/usr/src/app/openvpn.js:107:53)
    at /usr/src/app/openvpn.js:60:16
    at Array.forEach (<anonymous>)
    at Socket.<anonymous> (/usr/src/app/openvpn.js:58:13)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:268:9)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
``
