### ISSUE TITLE
Props tuncated issue

### ISSUE THREAD

**Issue by rajesh8614** [AuspeXeu/openvpn-status#460]
Using docker latest image

```
> openvpn-status@4.2.32 start /usr/src/app
> node server.js

Connected to management console @ 10.x.1.253:7505
Connected to management console @ 10.x.1.61:7506
props truncated ROUTING_TABLE   192.168
props truncated ROUTING_TABLE   192.168
props truncated ROUTING_TABLE   192.168
props truncated ROUTING_TABLE   192.168
props truncated ROUTING_TABLE   192.168
props truncated ROUTING_TABLE   192.168

```

**Comment by AuspeXeu** [comment]
Maybe @KarlStraussberger can help with this.

**Comment by KarlStraussberger** [comment]
**Works as disigned**. I don't know why the socket read returns before the end of the message but otherwise the application aborts in an exception.

It may be caused by openvpn itself because I observe similar issues in syslog as well. It can be a multithreading issue inside openvpn.

**Comment by rajesh8614** [comment]
Hi 
I am having this error again 

```Could not process data item ROUTING_TABLE       192.168.x.x    username 23.x.x.x:53989       Tue Apr 28 09:05:29 2020        1588044929
TypeError: Cannot read property 'split' of undefined
    at client.procData (/usr/src/app/openvpn.js:107:53)
    at /usr/src/app/openvpn.js:60:16
    at Array.forEach (<anonymous>)
    at Socket.<anonymous> (/usr/src/app/openvpn.js:58:13)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:268:9)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)```

**Comment by eJc2** [comment]
Hi, i have the same issue

Attaching to openvpn-status
openvpn-status    |
openvpn-status    | > openvpn-status@4.2.32 start /usr/src/app
openvpn-status    | > node server.js
openvpn-status    |
openvpn-status    | Connected to management console @ xxx.xxx.xxx.xxx:9994
openvpn-status    | props truncated ROUTING_TABLE       172.16.1.5
openvpn-status    | props truncated ROUTING_TABLE       172.16.1.5

Any hint?

**Comment by KarlStraussberger** [comment]
On our side socket.read returns too early so the remaining details are added to the next call. I do not know why this happens and when it startet. I just managed to stabilize the script. Maybe somebody can see the error already.

**Comment by eJc2** [comment]
thanks for reply, so openvpn responds too slow?

**Comment by KarlStraussberger** [comment]
Maybe, as soon as we know the reason, we can think about a solution.

**Comment by eJc2** [comment]
ok, thanks for your help
